computed_torque_controller:
    type: dual_franka_controllers/ComputedTorque
    arm_id: fr3
    joint_names:
         - fr3_joint1
         - fr3_joint2
         - fr3_joint3
         - fr3_joint4
         - fr3_joint5
         - fr3_joint6
         - fr3_joint7
    # --- Controller parameters --- #
    kp1: 300.0   #default: 120.0
    kp2: 150.0   #default: 70.0
    kp3: 30.0    #default: 50.0
    kv1: 30.0
    kv2: 15.0
    kv3: 3.0
    dt: 5

cartesian_impedance_controller_softbots:
    type: dual_franka_controllers/CartesianImpedanceControllerSoftbots
    arm_id: fr3
    joint_names:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
