computed_torque_controller:
    type: dual_franka_controllers/ComputedTorque
    arm_id: $(arg arm_id)
    joint_names:
         - $(arg arm_id)_joint1
         - $(arg arm_id)_joint2
         - $(arg arm_id)_joint3
         - $(arg arm_id)_joint4
         - $(arg arm_id)_joint5
         - $(arg arm_id)_joint6
         - $(arg arm_id)_joint7
    # --- Controller parameters --- #
    kp1: 300.0   #default: 120.0
    kp2: 150.0   #default: 70.0
    kp3: 30.0    #default: 50.0
    kv1: 30.0
    kv2: 15.0
    kv3: 3.0
    dt: 5

cartesian_impedance_controller_softbots:
    type: dual_franka_controllers/CartesianImpedanceControllerSoftbots
    arm_id: $(arg arm_id)
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7





